---

- name: Install dependencies packages
  package: name=unzip state=present

- name: Create Terraform directory
  file:
    path: "{{ terraform_dir }}"
    state: directory
    owner: "{{ ansible_ssh_user }}"
  register: terraform_directory

- name: Check terraform version
  shell: "terraform --version 2>&1 | grep {{terraform_version}}"
  failed_when: false
  changed_when: false
  register: terraform_versions_match

- name: Download terraform archive Linux 64 bits
  get_url:
    url: https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip
    dest: /tmp/terraform-{{terraform_version}}.zip
  when: "terraform_versions_match.rc != 0"

- name: Unarchive Terraform archive
  unarchive:
    src: /tmp/terraform-{{terraform_version}}.zip
    dest: "{{ terraform_dir }}"
    owner: "{{ ansible_ssh_user }}"
    remote_src: yes
  when: "terraform_versions_match.rc != 0 or terraform_directory |Â changed"

- name: Adding terraform command to user path
  file: 
    src: "{{terraform_dir}}/terraform"
    dest: /usr/bin/terraform
    state: link
